name: build java_openj9
on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *"  # bi-weekly on 1st and 15th calendar day at 17:00
  push:
    branches:
      - main
    paths:
      - java-openj9/**

permissions:
  actions: read
  packages: write

concurrency:
  group: java-openj9-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build_and_push:
    name: "java_${{ matrix.tag }}_openj9"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: 8
            platforms: linux/amd64,linux/arm64
          - tag: 11
            platforms: linux/amd64,linux/arm64
          - tag: 16
            platforms: linux/amd64
          - tag: 17
            platforms: linux/amd64,linux/arm64
          - tag: 18
            platforms: linux/amd64,linux/arm64
          - tag: 20
            platforms: linux/amd64,linux/arm64
          - tag: 21
            platforms: linux/amd64,linux/arm64

    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./java-openj9
          platforms: ${{ matrix.platforms }}
          file: ./java-openj9/${{ matrix.tag }}/Dockerfile
          push: true
          tags: ghcr.io/bijju089/panel-images:java_${{ matrix.tag }}_openj9
